[build]
builder = "nixpacks"
installCommand = "npm install"

[deploy]
startCommand = "npx prisma db push && npx prisma db seed && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
